POST http://localhost:4000/register
Content-Type: application/json

{
    "name":"madhu",
    "email":"madhu@gmail.com",
    "password":"madhu12"
}


###
POST http://localhost:4000/login/
Content-Type: application/json

{
    "email":"madhu@gmail.com",
    "password":"madhu12"
}

###
GET http://localhost:4000/getUserData/670caee0f3cc217ba8df8e94
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NzBjYWVlMGYzY2MyMTdiYThkZjhlOTQiLCJpYXQiOjE3Mjg4ODUzODIsImV4cCI6MTcyODg4ODk4Mn0.9olMCHixo0hqwlRXyPwphgAGpN5a-0UdhES44nP-ZRU

